### PR TITLE
Fixing mobile menus

### LINKED ISSUE #24: Menus not working on mobile
I was working on this issue without creating an issue. I've already committed a PR to fix it, but realized that I should have done this in a more transparent way to get feedback from other users. 

To demonstrate the problem, I created a simple fresh Backdrop CMS site using the latest release of Opera and added a few menu items. First without drop down menus and then with them. 

image

image

This is how the same site looks with Basis

image

image

### PR DESCRIPTION
**Pull request by stpaultim**
Fixes #24

### CODE REVIEW

**Comment by olafgrabienski** [comment]
@stpaultim May I ask what was the main issue with mobile menus? I'm using Opera as a sub-theme for one of my sites, and the mobile navigation on that site works fine for me. Now, the PR looks quite comprehensive, and I'm wondering where to look for when I update Opera and check the site afterwards.

**Comment by stpaultim** [comment]
@olafgrabienski I probably merged this too soon. But, I have not put it in a release. 

The problem I'm fixing was with one of my own sites that had a drop down menu. I don't think we had the necessary CSS for that scenerio. My solution, was simply to merge in some code used by basis that was not previously used in Opera. 

I do need to test this on some of my other sites using Opera.

**Comment by stpaultim** [comment]
NOTE: The bulk of this PR is just code copied from Basis. I did not review it in detail, it was a pretty much a copy and paste. 

I see that two other small changes snuck into this PR. 

There is a small change in the footer that was meant to fix an alignment issue, if there is more than one column in the footer. This fixed my situation, but I should do more testing on this change as well. 

The change to the header fixes a spacing gap that the code from Basis created. If I recall, my change is also consistent with how things work in Basis.

**Comment by olafgrabienski** [comment]
> The problem I'm fixing was with one of my own sites that had a drop down menu.

Thank you, good to know!

**Pull request merged**
